epochs: 50
batch_size: 16
learning_rate: 1e-3
print_freq: 50
train_script: cifar.py
data_dir: cifar-10
experiment_name: cifar_dist
cluster_name: dist-gpu
vm_size: STANDARD_NC24
num_nodes: 2
num_processes: 8
environment_name: AzureML-PyTorch-1.6-GPU
