epochs: 20
batch_size: 16
train_script: cifar.py
data_dir: cifar-10
experiment_name: cifar_dist_test
cluster_name: dist-gpu
vm_size: STANDARD_NC12
num_nodes: 2
num_processes: 4
environment_name: AzureML-PyTorch-1.6-GPU