epochs: 50
batch_size: 16
learning_rate: 1e-3
print_freq: 50
train_script: cifar.py
data_dir: cifar-10
experiment_name: demo
cluster_name: demo-compute
vm_size: STANDARD_NC6
num_nodes: 8
num_processes: 8
environment_name: AzureML-PyTorch-1.6-GPU
