epochs: 200
batch_size: 32
learning_rate: 1e-3
train_script: intel.py
data_dir: intel-image-classification
experiment_name: intel_dist_test
cluster_name: dist-gpu
vm_size: STANDARD_NC24
num_nodes: 4
num_processes: 16
environment_name: AzureML-PyTorch-1.6-GPU

