epochs: 50
batch_size: 32
learning_rate: 1e-3
print_freq: 50
train_script: intel.py
data_dir: intel-image-classification
experiment_name: intel_single
cluster_name: single-gpu
vm_size: STANDARD_NC6
num_nodes: 1
num_processes: 1
environment_name: AzureML-PyTorch-1.6-GPU
